### PR TITLE
Small code improvements

### PR DESCRIPTION
**Pull request by gabrielaradu**
User Case:
Send a PR with any improvement

Solution:
I am not a designer, but I wanted to add my small improvements to this.
I have taken into consideration to make the links accessable and use web safe colors. For more information about this please check: https://whocanuse.com/?b=3366FF&c=FFFFFF&f=20&s=
Extracting the colors and basic properties in a variables.css file makes it easier for later to modify all of them from one place only.

### CODE REVIEW

**Comment by jessfraz** [comment]
This looks great! Thank you so much, unfortunately since I am going in order of "first in, first to be merged" there is a conflict, do you mind fixing? Thank you!

**Comment by gabrielaradu** [comment]
I couldn't figure out how to update this particular PR after upstream update and I had to create a new one.

**Comment by jessfraz** [comment]
Seems like on mobile it looks a lot different now
Screenshot_20191204-065525

**Comment by gabrielaradu** [comment]
When I merged the conflicts I missed two variables. I have fixed that and updated the PR.

**Comment by gabrielaradu** [comment]
I took a look at the last merge made, the modifications introduced variables and i think this PR is no longer needed. But it was fun, thank you :)

**Comment by jessfraz** [comment]
Sorry about that, thank you so much!!!

**Pull request closed without merging**
