### PR TITLE
Modern centering & box-sizing

### PR DESCRIPTION
**Pull request by NikiSkaarup**
User Case:
Send a PR with any improvement

Solution:
Bugged me that position absolute and translate was being used for centering, so I rewrote those bits with flexbox and viewwidth and viewheight units, which have been supported by almost all browsers since 2012-2013.

And I added box-sizing for reduced mental book keeping for sizes.

All this causes a slight move of the text on desktop due to the slight off centering it had initially, even with compensation.

### CODE REVIEW

**Comment by jessfraz** [comment]
Looks great? Do you want to move this out of draft mode and into ready to review?

**Comment by NikiSkaarup** [comment]
Wups, I forgot make it a non draft, had set it to draft because I was still working on while writing it, but never submitted it before I was done anyway.

**Comment by jessfraz** [comment]
awesome thanks! can you fix the file conflict?

**Comment by jessfraz** [comment]
Awesome thank you!

**Pull request merged**
