### PR TITLE
Feature: Add Dark Mode Toggle

### PR DESCRIPTION
**Pull request by fivenp**
**What kind of change does this PR introduce?**

Since we all love dark mode toggles I thought we should have one here too... But to make sure we ain't scaring people away let's default to the known dark mode 😄 

- [x] ColorThemeSwitch which defaults to dark and saves it's settings to `localStorage` for recurring visits

**What did change?**

- [x] Fix some minor typography and responsiveness issues 
- [x] Abstract the CSS color definition a little bit to make it more themeable and also use vars instead of hardcoded colors across the css
- [x] Inline JS Code was moved from HTML to the js file

**What's in the pipeline/missing?**

- [ ] The Logo is a PNG and I'd like to avoid creating a second one for the `light mode` - any chance I could get an SVG version of the logo @jessfraz? (otherwise I go with the PNG approach)
- [ ] I'd potentially like to rewrite it as a react app since it would enable us to create reusable components and many more things - but I guess we'd need @jessfraz commitment on this ;)

**What is the current behavior/visual look?**

Before

**What is the new behavior/visual look?**

After - Dark Mode

After - Light Mode

**Checklist**

- [ ] Documentation
- [ ] Tests (ouch...)
- [ ] Ready to be merged

### CODE REVIEW

**Comment by fivenp** [comment]
Just realised I can't change the PR to a draft anymore after it was created 😢 

I'd like to add at least the logo to the light mode tho before we even think about merging this 😄

**Comment by jessfraz** [comment]
That looks amazing!

**Comment by jessfraz** [comment]
if I give you a logo that will work on the white version here, can that be updated as well :) this is awesome, thanks so much!
01 RGB Logo Oxide_Color

**Comment by jessfraz** [comment]
That's dope, thanks!

**Comment by fivenp** [comment]
Lol... You're faster than me adding a comment.... :D 
Best PR review I've ever had I guess....

**Pull request merged**
